#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
source  $OPENSHIFT_REPO_DIR/runtime.sh
rm -f /dev/shm/bdw-*
nohup broadwayd -p $OPENSHIFT_INTERNAL_PORT -a $OPENSHIFT_INTERNAL_IP > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &
sleep 3
nohup bash -c "while true; do launcher; done" > $OPENSHIFT_HOMEDIR/diy-0.1/logs/launcher.log 2>&1 &
