#!/bin/bash
# The logic to stop your application should be put in this script.
kill `ps -ef | grep broadwayd | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
kill `ps -ef | grep dbus-daemon | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
kill `ps -ef | grep launcher | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
