/* GENERATED BY testcodegen.py; DO NOT EDIT */


#ifndef __EVERYTHING_H__
#define __EVERYTHING_H__

#include <glib-object.h>

void
everything_nullfunc (void);


gboolean
everything_const_return_gboolean (void);


gint8
everything_const_return_gint8 (void);


guint8
everything_const_return_guint8 (void);


gint16
everything_const_return_gint16 (void);


guint16
everything_const_return_guint16 (void);


gint32
everything_const_return_gint32 (void);


guint32
everything_const_return_guint32 (void);


gint64
everything_const_return_gint64 (void);


guint64
everything_const_return_guint64 (void);


gchar
everything_const_return_gchar (void);


gshort
everything_const_return_gshort (void);


gushort
everything_const_return_gushort (void);


gint
everything_const_return_gint (void);


guint
everything_const_return_guint (void);


glong
everything_const_return_glong (void);


gulong
everything_const_return_gulong (void);


gsize
everything_const_return_gsize (void);


gssize
everything_const_return_gssize (void);


gintptr
everything_const_return_gintptr (void);


guintptr
everything_const_return_guintptr (void);


gfloat
everything_const_return_gfloat (void);


gdouble
everything_const_return_gdouble (void);


gunichar
everything_const_return_gunichar (void);


GType
everything_const_return_GType (void);


const gchar*
everything_const_return_utf8 (void);


const gchar*
everything_const_return_filename (void);


void
everything_oneparam_gboolean (gboolean arg0);


void
everything_oneparam_gint8 (gint8 arg0);


void
everything_oneparam_guint8 (guint8 arg0);


void
everything_oneparam_gint16 (gint16 arg0);


void
everything_oneparam_guint16 (guint16 arg0);


void
everything_oneparam_gint32 (gint32 arg0);


void
everything_oneparam_guint32 (guint32 arg0);


void
everything_oneparam_gint64 (gint64 arg0);


void
everything_oneparam_guint64 (guint64 arg0);


void
everything_oneparam_gchar (gchar arg0);


void
everything_oneparam_gshort (gshort arg0);


void
everything_oneparam_gushort (gushort arg0);


void
everything_oneparam_gint (gint arg0);


void
everything_oneparam_guint (guint arg0);


void
everything_oneparam_glong (glong arg0);


void
everything_oneparam_gulong (gulong arg0);


void
everything_oneparam_gsize (gsize arg0);


void
everything_oneparam_gssize (gssize arg0);


void
everything_oneparam_gintptr (gintptr arg0);


void
everything_oneparam_guintptr (guintptr arg0);


void
everything_oneparam_gfloat (gfloat arg0);


void
everything_oneparam_gdouble (gdouble arg0);


void
everything_oneparam_gunichar (gunichar arg0);


void
everything_oneparam_GType (GType arg0);


void
everything_oneparam_utf8 (const gchar* arg0);


void
everything_oneparam_filename (const gchar* arg0);


void
everything_one_outparam_gboolean (gboolean* arg0);


void
everything_one_outparam_gint8 (gint8* arg0);


void
everything_one_outparam_guint8 (guint8* arg0);


void
everything_one_outparam_gint16 (gint16* arg0);


void
everything_one_outparam_guint16 (guint16* arg0);


void
everything_one_outparam_gint32 (gint32* arg0);


void
everything_one_outparam_guint32 (guint32* arg0);


void
everything_one_outparam_gint64 (gint64* arg0);


void
everything_one_outparam_guint64 (guint64* arg0);


void
everything_one_outparam_gchar (gchar* arg0);


void
everything_one_outparam_gshort (gshort* arg0);


void
everything_one_outparam_gushort (gushort* arg0);


void
everything_one_outparam_gint (gint* arg0);


void
everything_one_outparam_guint (guint* arg0);


void
everything_one_outparam_glong (glong* arg0);


void
everything_one_outparam_gulong (gulong* arg0);


void
everything_one_outparam_gsize (gsize* arg0);


void
everything_one_outparam_gssize (gssize* arg0);


void
everything_one_outparam_gintptr (gintptr* arg0);


void
everything_one_outparam_guintptr (guintptr* arg0);


void
everything_one_outparam_gfloat (gfloat* arg0);


void
everything_one_outparam_gdouble (gdouble* arg0);


void
everything_one_outparam_gunichar (gunichar* arg0);


void
everything_one_outparam_GType (GType* arg0);


void
everything_one_outparam_utf8 (const gchar** arg0);


void
everything_one_outparam_filename (const gchar** arg0);


gboolean
everything_passthrough_one_gboolean (gboolean arg0);


gint8
everything_passthrough_one_gint8 (gint8 arg0);


guint8
everything_passthrough_one_guint8 (guint8 arg0);


gint16
everything_passthrough_one_gint16 (gint16 arg0);


guint16
everything_passthrough_one_guint16 (guint16 arg0);


gint32
everything_passthrough_one_gint32 (gint32 arg0);


guint32
everything_passthrough_one_guint32 (guint32 arg0);


gint64
everything_passthrough_one_gint64 (gint64 arg0);


guint64
everything_passthrough_one_guint64 (guint64 arg0);


gchar
everything_passthrough_one_gchar (gchar arg0);


gshort
everything_passthrough_one_gshort (gshort arg0);


gushort
everything_passthrough_one_gushort (gushort arg0);


gint
everything_passthrough_one_gint (gint arg0);


guint
everything_passthrough_one_guint (guint arg0);


glong
everything_passthrough_one_glong (glong arg0);


gulong
everything_passthrough_one_gulong (gulong arg0);


gsize
everything_passthrough_one_gsize (gsize arg0);


gssize
everything_passthrough_one_gssize (gssize arg0);


gintptr
everything_passthrough_one_gintptr (gintptr arg0);


guintptr
everything_passthrough_one_guintptr (guintptr arg0);


gfloat
everything_passthrough_one_gfloat (gfloat arg0);


gdouble
everything_passthrough_one_gdouble (gdouble arg0);


gunichar
everything_passthrough_one_gunichar (gunichar arg0);


GType
everything_passthrough_one_GType (GType arg0);


const gchar*
everything_passthrough_one_utf8 (const gchar* arg0);


const gchar*
everything_passthrough_one_filename (const gchar* arg0);

#endif
